call plug#begin('~/.vim/plugged')
Plug 'matthewtodd/vim-twilight'
Plug 'nanotech/jellybeans.vim'
Plug 'terryma/vim-multiple-cursors'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'kchmck/vim-coffee-script'
Plug 'rking/ag.vim'
Plug 'elzr/vim-json'
Plug 'tpope/vim-rails'
Plug 'vim-ruby/vim-ruby'
Plug 'elixir-editors/vim-elixir'
Plug 'tpope/vim-endwise'
Plug 'fatih/vim-go'
Plug 'thoughtbot/pick.vim'
Plug 'scrooloose/nerdtree'
call plug#end()
colorscheme Tomorrow-Night
set relativenumber
set clipboard=unnamedplus
set noswapfile
set term=screen-256color
set autoread
set tabstop=2
set shiftwidth=2
set expandtab "Use spaces even when tab key is used (Ctrl-V<Tab> will insert tab)
set hlsearch
set incsearch
let mapleader = " "
let g:netrw_liststyle=3
"Change cursor when in insert mode
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
"let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
let g:ctrlp_show_hidden = 1

"If AG is available, use it over grep for efficiency
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respect .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
endif

"Highlight white space in red at the end of a line, except when typing
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+\%#\@<!$/

"Remove extra space on save
autocmd BufWritePre * :%s/\s\+$//e

map <Leader>d :%s/\s\+$//<cr>
map <Leader>= gg=G
map <Leader>. <c-w>>
map <Leader>, <c-w><
map <Leader>r :set relativenumber<cr>
map <Leader>n :set number<cr>
"Set up Pick commands
nnoremap <Leader>p :call PickFile()<CR>
nnoremap <Leader>s :call PickFileSplit()<CR>
nnoremap <Leader>v :call PickFileVerticalSplit()<CR>

map <Leader>n :NERDTreeToggle<CR>
let NERDTreeShowLineNumbers=1
"Start Nerdtree when no file is specified
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

