export EDITOR="vim"

# Setup Autojump ("j" command)
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

alias dc="docker-compose"
alias dce="docker-compose exec"
alias groot='cd $(git rev-parse --show-toplevel)'

# Magic to pick a git branch (local)
alias gpl='git checkout $(git branch | cut -c 3- | pick)'
# Magic to pick a git branch (all: remote + local)
alias gpa='git checkout $(git branch -a | sed "s/remotes\/origin\///" | sort | uniq | pick)'

# Enable Chruby (Ruby Version Manager) & autoload current ruby version when cd to new project
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh
