export EDITOR="vim"

[[ -s "$HOME/.profile" ]] && source "$HOME/.profile" # Load the default .profile

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Setup Autojump ("j" command)
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

alias dc="docker-compose"
alias dce="docker-compose exec"
alias groot='cd $(git rev-parse --show-toplevel)'

# Shortcuts to open Terraform deployment files. Usage: vtf <dev | accp>
vtf () { vim ./infra/non-prod/$1/services/${PWD##*/}/terraform.tfvars; }
